In [1]:
import sklearn
import pandas as pd
import numpy as np
main_df = pd.read_csv(r"C:\Users\niraj\OneDrive\Desktop\imp files\ggg\extracurricular\scoresage beta\studentgrade.csv")

In [2]:
main_df.head(5)

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        4   0  11  11  
1      5        3      3     1     1      3        2   9  11  11  
2      4        3      2     2     3      3        6  12  13  12  
3      3        2      2     1     1      5        0  14  14  14  
4      4        3      2     1     2      5        0  11  13  13  

[5 rows x 33 columns]

In [16]:
cols=['famrel','freetime','goout','Dalc','Walc','health','absences']
dfx = main_df[cols]
c2= ['G1']
dfy=main_df[c2]
dfx.head(5)


famrel  freetime  goout  Dalc  Walc  health  absences
0       4         3      4     1     1       3         4
1       5         3      3     1     1       3         2
2       4         3      2     2     3       3         6
3       3         2      2     1     1       5         0
4       4         3      2     1     2       5         0

In [17]:
dfy.head(5)

G1
0   0
1   9
2  12
3  14
4  11

In [25]:
#multiple leniar regressor
from sklearn.linear_model import SGDRegressor
model = SGDRegressor(max_iter = 10000)


In [26]:
model.fit(dfx,dfy)

C:\Users\niraj\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDRegressor(max_iter=10000)

In [27]:
model.predict(dfx.head(1))

array([11.34770072])

logistic regressor

In [44]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=1000)


In [45]:
from sklearn.datasets import load_iris

In [46]:
iris=load_iris()

In [47]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [64]:
df= pd.DataFrame(iris.data,columns = iris.feature_names)
df1= df
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [65]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [66]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [67]:
df['target']=iris.target
df['flower_names']=df.target.apply(lambda x:iris.target_names[x])

In [68]:
df.flower_names

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: flower_names, Length: 150, dtype: object

In [71]:
tds= ['target','flower_names']
df1= df.drop(tds, axis='columns')
df1

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [72]:
model.fit(df1,df['target'])

LogisticRegression(max_iter=1000)

In [73]:
model.predict(df1.head(1))

array([0])

In [74]:
df.head(1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   

   target flower_names  
0       0       setosa

simple linear regressor

In [75]:
main_df

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
644     MS   F   19       R     GT3       T     2     3  services     other   
645     MS   F   18       U     LE3       T     3     1   teacher  services   
646     MS   F   18       U     GT3       T     1     1     other     other   
647     MS   M   17       U     LE3       T     3     1  services  services   
648     MS   M   18       R     LE3       T     3     2  services     other   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        4   0  11  11  
1    ...      5        3      3     1     1      3        2   9  11  11  
2    ...      4        3      2     2     3      3        6  12  13  12  
3    ...      3        2      2     1     1      5        0  14  14  14  
4    ...      4        3      2     1     2      5        0  11  13  13  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
644  ...      5        4      2     1     2      5        4  10  11  10  
645  ...      4        3      4     1     1      1        4  15  15  16  
646  ...      1        1      1     1     1      5        6  11  12   9  
647  ...      2        4      5     3     4      2        6  10  10  10  
648  ...      4        4      1     3     4      5        4  10  11  11  

[649 rows x 33 columns]

In [76]:
dfx

famrel  freetime  goout  Dalc  Walc  health  absences
0         4         3      4     1     1       3         4
1         5         3      3     1     1       3         2
2         4         3      2     2     3       3         6
3         3         2      2     1     1       5         0
4         4         3      2     1     2       5         0
..      ...       ...    ...   ...   ...     ...       ...
644       5         4      2     1     2       5         4
645       4         3      4     1     1       1         4
646       1         1      1     1     1       5         6
647       2         4      5     3     4       2         6
648       4         4      1     3     4       5         4

[649 rows x 7 columns]

In [77]:
dfy

G1
0     0
1     9
2    12
3    14
4    11
..   ..
644  10
645  15
646  11
647  10
648  10

[649 rows x 1 columns]

In [78]:
from sklearn.linear_model import LinearRegression

In [84]:
import numpy as np
w=np.array(dfx['famrel'])
model = LinearRegression()
model.fit(w.reshape(-1,1),dfy)

LinearRegression()

In [85]:
w

array([4, 5, 4, 3, 4, 5, 4, 4, 4, 5, 3, 5, 4, 5, 4, 4, 3, 5, 5, 3, 4, 5,
       4, 5, 4, 1, 4, 2, 5, 4, 5, 4, 4, 5, 5, 3, 5, 2, 4, 4, 3, 5, 4, 5,
       4, 5, 2, 4, 4, 4, 4, 4, 5, 3, 5, 5, 4, 3, 4, 4, 2, 5, 4, 3, 4, 5,
       1, 4, 4, 4, 4, 3, 3, 5, 4, 4, 3, 5, 4, 2, 3, 5, 4, 5, 4, 4, 4, 5,
       4, 4, 4, 4, 3, 5, 4, 3, 3, 4, 5, 5, 4, 4, 5, 4, 5, 4, 5, 5, 1, 5,
       5, 4, 3, 3, 5, 5, 4, 5, 5, 3, 3, 5, 4, 3, 5, 5, 5, 3, 3, 3, 4, 5,
       3, 4, 3, 3, 3, 5, 5, 4, 5, 5, 3, 4, 3, 4, 4, 4, 5, 2, 1, 5, 2, 4,
       3, 5, 4, 4, 3, 4, 2, 3, 4, 2, 4, 4, 4, 4, 4, 2, 5, 4, 4, 4, 3, 4,
       4, 5, 5, 4, 4, 4, 5, 4, 3, 4, 4, 4, 4, 4, 3, 4, 4, 5, 3, 4, 5, 5,
       1, 4, 3, 4, 3, 3, 4, 5, 4, 4, 5, 4, 5, 3, 4, 4, 4, 4, 4, 5, 5, 4,
       2, 1, 4, 4, 4, 5, 3, 4, 5, 4, 3, 3, 3, 4, 4, 4, 2, 3, 5, 5, 5, 5,
       4, 3, 3, 4, 4, 4, 3, 5, 4, 4, 5, 4, 5, 4, 4, 4, 5, 4, 5, 2, 5, 5,
       3, 4, 4, 2, 3, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5, 5, 4, 4, 4, 5, 3, 3,
       4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 5, 5, 3, 1, 3,

In [87]:
model.predict(w[0].reshape(-1,1))

array([[11.4087939]])

DECISION TREES


In [88]:
from sklearn.tree import DecisionTreeRegressor
dfx

famrel  freetime  goout  Dalc  Walc  health  absences
0         4         3      4     1     1       3         4
1         5         3      3     1     1       3         2
2         4         3      2     2     3       3         6
3         3         2      2     1     1       5         0
4         4         3      2     1     2       5         0
..      ...       ...    ...   ...   ...     ...       ...
644       5         4      2     1     2       5         4
645       4         3      4     1     1       1         4
646       1         1      1     1     1       5         6
647       2         4      5     3     4       2         6
648       4         4      1     3     4       5         4

[649 rows x 7 columns]

DECISION TREE REGRESSOR

In [89]:
model = DecisionTreeRegressor()
model.fit(dfx,dfy)

DecisionTreeRegressor()

In [90]:
model.predict(dfx.head(1))

array([0.])

In [91]:
main_df.head(1)

school sex  age address famsize Pstatus  Medu  Fedu     Mjob     Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home  teacher  ...   

  famrel freetime  goout  Dalc  Walc health absences G1  G2  G3  
0      4        3      4     1     1      3        4  0  11  11  

[1 rows x 33 columns]